# Site settings
# in the templates available like {{ site.myvariable }}.
future: true
title: Clean portfolio theme for Jekyll powered by Bootstrap 4.
email: your-email@domain.com
brand: Saranya B Mangal
headline: Veena player, Singer and Engineer
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
copyright: 2016 Whatever Company, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: harinp715@gmail.com
phone: +91 8095488800

# Tracking
googleAnalitycsID: UA-129702446-1

